# Generated by Django 5.1.7 on 2025-03-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanka', '0002_tankapost_tankacomment_tankalike'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankaStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned_tanka_count', models.IntegerField(default=0)),
                ('generated_tanka_count', models.IntegerField(default=0)),
            ],
        ),
    ]
