# Generated by Django 5.1.7 on 2025-03-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanka', '0003_tankastatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankachat',
            name='is_ai_response',
            field=models.BooleanField(default=False),
        ),
    ]
