# Generated by Django 5.1.7 on 2025-03-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanka', '0004_tankachat_is_ai_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankachat',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
